## Векторы

In [131]:
import numpy as np
import pandas as pd

In [132]:
s = np.array([33, 65, 50, 45])
s

array([33, 65, 50, 45])

In [133]:
s[2]

50

In [134]:
len(s)

4

In [135]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 19, 9, 7])
print(a+b)
print(a-b)

[15 27 14  8]
[  5 -11  -4  -6]


In [136]:
a = np.array([120, 45, 68])
omega = .2
c = a * omega
print(c)

[24.   9.  13.6]


In [137]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100 
omega3 = 0
u = p*omega1 + v*omega2 + s*omega3
u

array([1800, 3000, 2700])

In [138]:
a = np.array([65, 70, 120, 30])
w = np.array([.4, .4, .2, .8])
np.dot(a, w)

102.0

In [139]:
x = [1, 2, 3]
x_arr = np.array(x, dtype=float)
print(x, type(x))
print(x_arr, type(x_arr))
print(x_arr)

[1, 2, 3] <class 'list'>
[1. 2. 3.] <class 'numpy.ndarray'>
[1. 2. 3.]


In [140]:
# Нулевой вектор.
x_zero = np.zeros(8)
x_zero

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [141]:
x_one = np.ones(4)
x_one

array([1., 1., 1., 1.])

In [142]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [143]:
np.random.randint(-3, 10, 7)

array([ 8,  2,  0,  3,  7, -3,  2])

In [144]:
d = {
    '$$' : [65, 70,  120, 35],
     '2.Area' : [50, 52,  80, 33],
     '3.Rooms' : [3, 2, 1, 1],
     '4.Floor' : [5, 12, 10, 3],
     '5.Demo' : [8, 4, 5, 10]
     }
df = pd.DataFrame(d)
df

$$  2.Area  3.Rooms  4.Floor  5.Demo
0   65      50        3        5       8
1   70      52        2       12       4
2  120      80        1       10       5
3   35      33        1        3      10

In [145]:
A = df.values
A

array([[ 65,  50,   3,   5,   8],
       [ 70,  52,   2,  12,   4],
       [120,  80,   1,  10,   5],
       [ 35,  33,   1,   3,  10]], dtype=int64)

In [146]:
print(A[1])
print(A[:, 3])

[70 52  2 12  4]
[ 5 12 10  3]


In [147]:
a = np.array([1, 2, 3])
b = np.array([6, 7, 8])
c = np.array([1, 0, 1])
d = 2*a + 2*b + 3*c
d

array([17, 18, 25])

In [148]:
# Склярное произведение.
np.dot(a, b)

44

In [149]:
a@b

44

In [150]:
# Длина вектора.
np.linalg.norm(a)

3.7416573867739413

In [151]:
# Нормировка.
a_norm = a / np.linalg.norm(a)
np.linalg.norm(a_norm)

1.0

## Матрицы

In [152]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [153]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [154]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [155]:
diagonal = [1, 2, 3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [156]:
5 * np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [157]:
A = np.array([[1, 1], [2, 3], [5, 7]])
A

array([[1, 1],
       [2, 3],
       [5, 7]])

In [158]:
B = A.T
B

array([[1, 2, 5],
       [1, 3, 7]])

In [159]:
B.T

array([[1, 1],
       [2, 3],
       [5, 7]])

In [160]:
A = np.matrix('1, -5; 2, 2; 0, 3')
B = np.matrix('3, 1, 0; -1, 0, 2')
print(A)
print()
print(B)
print()
print(np.dot(A, B))

[[ 1 -5]
 [ 2  2]
 [ 0  3]]

[[ 3  1  0]
 [-1  0  2]]

[[  8   1 -10]
 [  4   2   4]
 [ -3   0   6]]


In [161]:
A@B

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [162]:
A = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 10')
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [163]:
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [164]:
np.linalg.det(A)

-2.9999999999999996

In [165]:
v1 = np.array([1, 2, 3, 1])
v2 = np.array([4, 5, 6, 1])
v3 = np.array([7, 8, 9, 1])
A = np.array([v1, v2, v3]).T
print(A)
print(np.linalg.matrix_rank(A))

[[1 4 7]
 [2 5 8]
 [3 6 9]
 [1 1 1]]
2


In [166]:
v1 = np.array([1, 2, 3, 1])
v2 = np.array([4, 5, 6, 1])
v3 = np.array([7, 8, 10, 1])
A = np.array([v1, v2, v3]).T
print(A)
print(np.linalg.matrix_rank(A))

[[ 1  4  7]
 [ 2  5  8]
 [ 3  6 10]
 [ 1  1  1]]
3


In [167]:
A = np.array([
    [1, 2],
    [3, 7]
])
np.linalg.inv(A)

array([[ 7., -2.],
       [-3.,  1.]])

In [168]:
v1 = np.array([2, 10, -2])
v2 = np.array([3, 2, -2])
v3 = np.array([8, 14, -6])
A = np.array([v1, v2, v3]).T
np.linalg.matrix_rank(A)

2

In [169]:
v = np.array([5, 1, 2])
u = np.array([4, 2, 8])
np.corrcoef(v, u)

array([[1.        , 0.05241424],
       [0.05241424, 1.        ]])

In [170]:
x1 = np.array([5.1, 1.8, 2.1, 10.3, 12.1, 12.6])
x2 = np.array([10.2, 3.7, 4.1, 20.5, 24.2, 24.1])
x3 = np.array([2.5, 0.9, 1.1, 5.1, 6.1, 6.3])
A = np.array([x1, x2, x3])
A

array([[ 5.1,  1.8,  2.1, 10.3, 12.1, 12.6],
       [10.2,  3.7,  4.1, 20.5, 24.2, 24.1],
       [ 2.5,  0.9,  1.1,  5.1,  6.1,  6.3]])

In [171]:
A_corr = np.corrcoef(A)
print(A_corr)

[[1.         0.99925473 0.99983661]
 [0.99925473 1.         0.99906626]
 [0.99983661 0.99906626 1.        ]]


In [172]:
np.linalg.matrix_rank(A_corr)

3

In [176]:
print(np.round(np.linalg.det(A_corr), 7))

5e-07


In [177]:
print('Determinant: {:.7f}'.format(np.linalg.det(A_corr)))

Determinant: 0.0000005
