## Векторы

In [1]:
import numpy as np
import pandas as pd

In [2]:
s = np.array([33, 65, 50, 45])
s

array([33, 65, 50, 45])

In [3]:
s[2]

50

In [4]:
len(s)

4

In [5]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 19, 9, 7])
print(a+b)
print(a-b)

[15 27 14  8]
[  5 -11  -4  -6]


In [6]:
a = np.array([120, 45, 68])
omega = .2
c = a * omega
print(c)

[24.   9.  13.6]


In [7]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100 
omega3 = 0
u = p*omega1 + v*omega2 + s*omega3
u

array([1800, 3000, 2700])

In [8]:
a = np.array([65, 70, 120, 30])
w = np.array([.4, .4, .2, .8])
np.dot(a, w)

102.0

In [9]:
x = [1, 2, 3]
x_arr = np.array(x, dtype=float)
print(x, type(x))
print(x_arr, type(x_arr))
print(x_arr)

[1, 2, 3] <class 'list'>
[1. 2. 3.] <class 'numpy.ndarray'>
[1. 2. 3.]


In [10]:
# Нулевой вектор.
x_zero = np.zeros(8)
x_zero

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
x_one = np.ones(4)
x_one

array([1., 1., 1., 1.])

In [13]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [17]:
np.random.randint(-3, 10, 7)

array([ 3,  2,  9, -3,  5,  5,  8])

In [18]:
d = {
    '$$' : [65, 70,  120, 35],
     '2.Area' : [50, 52,  80, 33],
     '3.Rooms' : [3, 2, 1, 1],
     '4.Floor' : [5, 12, 10, 3],
     '5.Demo' : [8, 4, 5, 10]
     }
df = pd.DataFrame(d)
df

$$  2.Area  3.Rooms  4.Floor  5.Demo
0   65      50        3        5       8
1   70      52        2       12       4
2  120      80        1       10       5
3   35      33        1        3      10

In [19]:
A = df.values
A

array([[ 65,  50,   3,   5,   8],
       [ 70,  52,   2,  12,   4],
       [120,  80,   1,  10,   5],
       [ 35,  33,   1,   3,  10]], dtype=int64)

In [21]:
print(A[1])
print(A[:, 3])

[70 52  2 12  4]
[ 5 12 10  3]


In [22]:
a = np.array([1, 2, 3])
b = np.array([6, 7, 8])
c = np.array([1, 0, 1])
d = 2*a + 2*b + 3*c
d

array([17, 18, 25])

In [23]:
# Склярное произведение.
np.dot(a, b)

44

In [24]:
a@b

44

In [25]:
# Длина вектора.
np.linalg.norm(a)

3.7416573867739413

In [27]:
# Нормировка.
a_norm = a / np.linalg.norm(a)
np.linalg.norm(a_norm)

1.0