## Векторы

In [3]:
import numpy as np

In [4]:
s = np.array([33, 65, 50, 45])
s

array([33, 65, 50, 45])

In [5]:
s[2]

50

In [6]:
len(s)

4

In [7]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 19, 9, 7])
print(a+b)
print(a-b)

[15 27 14  8]
[  5 -11  -4  -6]


In [8]:
a = np.array([120, 45, 68])
omega = .2
c = a * omega
print(c)

[24.   9.  13.6]


In [9]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100 
omega3 = 0
u = p*omega1 + v*omega2 + s*omega3
u

array([1800, 3000, 2700])

In [10]:
a = np.array([65, 70, 120, 30])
w = np.array([.4, .4, .2, .8])
np.dot(a, w)

102.0